#!/bin/sh

set -e

case $1 in
    configure)
        if ! getent passwd etcd > /dev/null 2>&1 ; then
            adduser --system --group --disabled-login --disabled-password --home /var/lib/etcd/ etcd
        fi
        chmod 700 /var/lib/etcd/

	if [ -x "/etc/init.d/etcd" ] || [ -e "/etc/init/etcd.conf" ]; then
		if [ ! -e "/etc/init/etcd.conf" ]; then
			update-rc.d etcd defaults >/dev/null
		fi
		invoke-rc.d etcd start || exit $?
	fi
    ;;
    abort-upgrade|abort-remove|abort-deconfigure)
    ;;
    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#
